jorgerojas26/lazysql

components/ConnectionForm.go
components/ConnectionSelection.go
components/Home.go
drivers/mysql.go
drivers/postgres.go
drivers/sqlite.go
helpers/utils.go
models/models.go

This resolves #25, #30, #31, #32, #33, #34.
The user is now responsible of properly escaping the url connection string.
Lazysql rely primarily on [xo/dburl](https://github.com/xo/dburl?tab=readme-ov-file#url-parsing-rules), and as such, parsing or opening database connection URLs with Lazysql are subject to the same rules, conventions, and semantics.
For examples of supported URLs please see: https://github.com/xo/dburl?tab=readme-ov-file#example-urls

Reverts internal URL escaping

---

components/ResultsTable.go
drivers/driver.go
drivers/mysql.go
drivers/postgres.go
drivers/sqlite.go
models/models.go

DML statements "where" condition were using a hardcoded "id" column, which of course did not work for tables that do not have an "id" column.
So, instead of hardcoding the where condition, now we find a primary key column name and for every DML statement we pass that column name and value, so it is required to have a primary key on the table to perform DML updates in this version.
Maybe later we can improve that logic requesting the user to introduce the `where` condition in a popup if there is no a primary key, but for now i think this works.
Fixes #35

refactor: replaces "where" logic in DML statements

---

components/ResultsTable.go
components/Tree.go
drivers/postgres.go

**Add support for different schemas in postgresql and add support for uuid primary keys**
I have two schemas in the same postgresql database with the same table name. One table is in the public schema, and the other in a test schema. Currently records are only fetched from the table in the public schema and constraints and foreign keys are fetched for both tables.
Also, when editing a cell, the current code uses next_val to find the primary key, but my table uses uuids as the primary key, so no primary key is found resulting in a missing where clause.
Add schema prefix to all operations in the postgres driver.
Don't rely on next_val for the primary key column and instead look for a column with the primary key constraint.

Support tables in different schemas

---

main.go

When I use the lazygit, I find that there is a  mouse action feature can be enabled ,  the go package `github.com/rivo/tview` support this function itself , only to add one line code before calling Run() function.  And it seems greate to enable this, then I can use mouse click to check the database and chart.

feat: enable mouse actions when interact with lazysql terminal UI

---

components/ResultsTable.go

1. fix perminately blocked when operate a empty table. issue: #54
2. replaced variable `rune  := event.Rune()` with `eventKey := event.Rune()` , since rune is a build in key word of golang, it is a build in type,   so this is not a good idea to use it as a variable .

fix: fix perminately blocked when operate a empty table. issue: #54

---

README.md

fix:  according to the source code , when navigate the database and table tree,, there are 2  more keys avaiable， but they are not shown in the README, so I add then in README to let user know this feature
> **components/Tree.go**
```
tree.SetInputCapture(func(event *tcell.EventKey) *tcell.EventKey {
switch event.Rune() {
case 'G':
childrens := tree.GetRoot().GetChildren()
lastNode := childrens[len(childrens)-1]
if lastNode.IsExpanded() {
childNodes := lastNode.GetChildren()
lastChildren := childNodes[len(childNodes)-1]
tree.SetCurrentNode(lastChildren)
} else {
tree.SetCurrentNode(lastNode)
}
case 'g':
tree.SetCurrentNode(rootNode)
}
return event
})
```

fix: add keybindings info accroding to source code

---

README.md
components/SQLEditor.go

>  Added support for external editors while in SQL editor.
>  Users can set $SQL_EDITOR for specific editor.
>  Opens another terminal for external editor.
> Users can set $SQL_TERMINAL for specific editor.
> Added keybindings for external editor in README.
> Creates temporary file (lazysql.sql) in current working directory.
> Currently, this feature is supported only for linux.

[Feat] Added support for external editor (2)

---

drivers/mysql.go

fix: format table name to include backticks

---

components/Home.go
components/ResultsTable.go
drivers/postgres.go

Fixes not being able to connect to other databases than the default one (postgres) using the Tree when connecting to an instance using a connection string without database name at the end.
Also, Fixes #64.

Postgres connections fix

---

.github/workflows/release.yml
.goreleaser.yaml
README.md
main.go

Add homebrew tap

---

.github/workflows/release.yml
.golangci.yml
app/Keymap.go
components/ConnectionForm.go
components/ConnectionPage.go
components/ConnectionSelection.go
components/ConnectionsTable.go
components/Home.go
components/ResultTableFilter.go
components/ResultsTable.go
components/SQLEditor.go
components/Tree.go
drivers/mysql.go
drivers/postgres.go
drivers/sqlite.go
go.mod
go.sum
helpers/config.go
keymap/map.go
main.go

- **chore: use Go canonical way to return errors**
- **chore: use the canonical name for error variable**
- **ci: add golangci-lint configuration file**
- **fix: catch errors reported by errcheck linter**
- **fix: make sure to catch all errors in drivers**
- **ci: enable more linters**
- **chore: fix import orders**
- **chore: remove dot import and use type alias**
- **chore: remove else when previous if ends with a return**
- **chore: remove type or default value when obvious**
- **chore: use go initialism for variable name**
- **chore: no uppercase constant in Go**
- **chore: remove suspicious blank imports**
- **fix: make sure to use the database name when getting table columns**
- **ci: enable golang-lint in GitHub actions**
Fixes #71 
Related to #14

golangci lint

---

README.md
app/Keymap.go
commands/commands.go
components/ConnectionSelection.go
components/Home.go
components/Tree.go

1. Add an input to search on the tree
2. Add `n` and `p` keybindings on the tree to cycle between found nodes.
- `n` = Next
- `p` = Previous
3. Add `c` and `e` keybindings on the tree to collapse and expand all nodes
- `c` = collapse all
- `e` = expand all
Fixes #83

feat: add input filter to tree

---

drivers/mysql.go
drivers/postgres.go
drivers/sqlite.go
drivers/utils.go
drivers/utils_test.go
go.mod
go.sum

`(*sql.Rows).Next()` can return `false` due to an error. The error must be handled by checking `(*sql.Rows).Err()`.
The transaction must be ended by commit or rollback to close the db connection. Calling rollback after commit is noop.
Don't call a query in the middle of cursor, as it may lead to a deadlock. The inner query may wait for a free connection, and the connection from the cursor can't be freed because it's stuck by the inner query waiting.

fix: error handing for row cursors

---

app/App.go
app/Keymap.go
commands/commands.go
components/ConfirmationModal.go
components/ConnectionForm.go
components/ConnectionPage.go
components/ConnectionSelection.go
components/ConnectionsTable.go
components/HelpModal.go
components/HelpStatus.go
components/Home.go
components/Pages.go
components/ResultTableFilter.go
components/ResultsTable.go
components/ResultsTableMenu.go
components/SQLEditor.go
components/Sidebar.go
components/TabbedMenu.go
components/Tree.go
components/constants.go
drivers/constants.go
drivers/mysql.go
drivers/postgres.go
drivers/sqlite.go
drivers/utils_test.go
models/models.go

The main idea here is to have that toggleable sidebar that shows the table results in a vertical manner, so it is easy to see all the columns.

Add a toggleable sidebar to view records

---

README.md
app/Keymap.go
commands/commands.go
components/ResultsTable.go

This pull request introduces a new feature that allows users to refresh the current table view in the application.
The changes include:
- Added refresh func to fetch latest data.
- Updated UI for refreshed state.
- Reduced redundant database calls.
Closes [#97](https://github.com/jorgerojas26/lazysql/issues/97)
- Please ensure to test the refresh feature thoroughly in different scenarios.

feat: refresh the current table.

---

components/ConfirmationModal.go

At least in my terminal I was not able to see the active button so choosing `yes` or `no` felt like a gamble 😉

Make the active button stand out in more terminal themes

---

components/ResultsTable.go
drivers/postgres.go

Sorry for all the PRs, I'm just having fun with it and am hitting a lot of small issues when using `lazysql` which I would like to help improve 😉 
This PR removes all the calls to `recover` as it is very discouraged (see Go docs) to try and recover panics as in in 99.999999% of the cases that indicates a bug in the program or another error not being handled properly which should be fixed instead.
In order to take any actions using a `defer` that will only do something if the function returned an error, its best to just check against that error. While in Go its no too common to use named return values in the function signature, in the case where you want a defer to have access to the actual returned value I found it to be the most robust to at least name the error in the function …

Do not try to recover from panics, but use the return values

---

drivers/postgres.go

Not sure if/how this worked for other users, but for my setup (using named schemas) this didn't work. By taking the schema name into account when doing the query it now works great for all use cases (as far as I could test/verify).

Fix query to get primary column names for postgres

---

app/Keymap.go
commands/commands.go
components/Tree.go

This PR should fix #118 
To refresh the tree view my idea is to:
1. clear existing nodes (under root)
2. Re-initialize nodes (under root)
3. Reset search state
4. Close opened table if it no longer exists

feat: Refresh tree shortcut

---

README.md
components/ArgConnection.go
main.go

Thanks for the amazing tool! 
I'd like to see a feature like this get merged as I find it easier to just pass the path to the database I want to open as an argument, so I made this request. This implementation works but perhaps is doing a bit too much in the main.go file. I first tried doing most of this connection initialization inside Pages.go but the init() functions run before main.go's main() function.
I'd love to hear your feedback on this!

Add connecting to database by connectionString given as an argument to cli

---

README.md

I wrote some mini-tutorials about how to get started using `lazysql` as described in #117 
To be more precise i wrote 'tutorials' for:
- Connecting to a DB
- Creating a table (redirect to SQL Editor)
- Execute SQL querys
- Open / View a table
- Filter rows
- Insert rows
- Edit a column
I would love to know what you think about the phrasing, the general style and if you would want me to change.

Improved usage information

---

components/pagination.go

The local offset variable is increased by 1 so the records start at 1 instead of at 0. But that should not be taken into account when calculating the record number of the last fetched record...

Use the "real" offset to calculate the currently shown records

---

components/pagination.go
components/results_table.go
drivers/driver.go
drivers/mssqql.go
drivers/mysql.go
drivers/postgres.go
drivers/sqlite.go

They previously didn't take the row with column names into account and I noticed there are actually 3 slightly different methods that calculate the pagination info, while I previously just updated/fixed one of them
The second commit changes the way how the SQL editor behaves a little as I continuously found myself doing the wrong thing here because the behavior was different depending on the result. If there were results the focus would switch to the table, if not it would stay with the editor.
While I understand that in some flows that makes sense as you might want to update your query and try again, but in a lot of other flows you might want to return to the tree or open another DB or...
So I thought it would easier for peoples' muscle memory to learn one consistent flow instead of …

Update the pagination logic for queries done from the SQL editor

---

README.md
app/config.go
components/results_table.go
models/models.go

The main idea of this PR is to add an offset layout to the sidebar, so users can choose between offset and overlay layout as they want with the new `SidebarOverlay` config option.
Also, the default value for `SidebarOverlay` is false, so the offset layout is the default now.
Offset layout:
Overlay layout:
Fixes #160

feat: add offset layout to the sidebar

---

.golangci.yml
components/tree.go

This PR modifies the search function to allow filtering of tree nodes based on both database name and table name.
The search text is split into two parts, with the first part being treated as the database name filter and the second part as the table name filter.
This allows users to more easily find specific nodes within the tree.
With one word
With two words
Fix #121

feat: add search pattern dbName + tableName

---

README.md
app/keymap.go

This is a breaking change
The issue is that query editor doesn't allow to enter [] characters because they are bound to tab navigation
I'm not sure if this is the best way to fix it but it works and seems sensible.

change keybind from [] to ctrl+[] for navigation between tabs

---

components/connection_page.go
components/pages.go
models/models.go

Makes the connection selector page full screen on small window sizes and on larger sizes, a centered box as always, just a bit bigger.
Fixes #148

feat: Implement responsive grid layout for connection pages

---

README.md
components/connection_selection.go
helpers/command.go
models/models.go

Implements: #156
Any thoughts on the `SaveOutputTo` field name?
I'm also not in love with the `waitToCaptureVariable` solution. I think it would make more sense for the `helpers.RunCommand` to return a `<- chan string` with the output, and then we could `onDone := App.Register(); go func() { _ = <- c; onDone() }()`. In other words, `RunCommand` doesn't take in the `onDone` callback; it just gives out a channel which we can use to synchronize. I didn't feel like it was important enough to figure it out here though.  
Similarly, I'm unhappy with the `io.MultiWriter` usage. It feels a bit hacky to me.
Also, in case you're curious, here's my original use case for this feature: I have two MSSQL instances on my machine. If you have just one, it's typically on `localhost:1433`, but with two, …

Implement user-define variables
